### ISSUE TITLE
Consider limiting Player.name to 12 bytes

### ISSUE THREAD

**Issue by veox** [Great-Hill-Corporation/nameGame#10]
This is completely superficial and can be ignored unless you want to make use of [storage packing](https://solidity.readthedocs.io/en/develop/miscellaneous.html#layout-of-state-variables-in-storage).

Since a `Player` struct [has 20 bytes used](https://solidity.readthedocs.io/en/develop/types.html#arrays) for `addr`, there are 12 bytes that are left over for `name` that can be still packed into the same storage slot for the same gas price.

This may be tricky and would probably be safest with `bytes12`. Since you're already checking for zero-length strings, I assume you're aware of the difficulties, but will link [the Arrays section](https://solidity.readthedocs.io/en/develop/types.html#arrays) just in case.

**Comment by tjayrush** [comment]
Wow. I love that you're thinking about gas. I think I'm going to ignore this, but save the discussion of gas for my Solidity 102 class. (Which doesn't exist, yet).
