### ISSUE TITLE
Obsolete throw on default function 

### ISSUE THREAD

**Issue by o0ragman0o** [Great-Hill-Corporation/nameGame#2]
```
    function () {
        // Do not allow straight sending of ether, otherwise it will get lost forever
        throw;
    }
```

This check is no longer required as of Solidity 0.4.0.  Contracts that wish to accept value to the default function now have to use the `payable` modifier.

**Comment by tjayrush** [comment]
Question for you. Is it true to say that if one does not provide a default function (i.e. function()) then no-one can inadvertently send ether to the contract? In other words, I can just delete the function as long as it is not 'payable'?

**Comment by o0ragman0o** [comment]
Yes, as of Solidity version 0.4.0 undefined default functions will throw.

**Comment by tjayrush** [comment]
I'll close this and remove it. Thanks.
