### ISSUE TITLE
Consider public state variables

### ISSUE THREAD

**Issue by o0ragman0o** [Great-Hill-Corporation/nameGame#4]
```
    struct Player {
        string name;
        address addr;
    }

    Player [] players;
    uint nPlayers;
    uint public nNeeded;

    uint current;
    uint public entryFee;
    uint endTime;
    uint dur;

    address owner;
```

Certain game parameters such as the required entry fee and the number of players needed should be publicly viewable for potential players to enter the game with the correct value.

The `public` modifier on a state variable creates *[accessor functions](http://solidity.readthedocs.io/en/develop/contracts.html#accessor-functions)*, IOW public getter functions of the name of the state variable itself.

e.g.
```
uint public entryFee;
// The accessor function is automatically generated as... 
function entryFee() public returns (uint) { return entryFee; }
```

**Comment by tjayrush** [comment]
Accepted. Change made.
