### ISSUE TITLE
Block timestamps are not realiable time sources

### ISSUE THREAD

**Issue by o0ragman0o** [Great-Hill-Corporation/nameGame#5]
```
    function NameGame(uint _n, uint _dur, uint _entryFee) {
        nNeeded = (_n < 2 ? 2 : (_n > 5 ? 5 : _n));
        dur = (_dur < 30 ? 30 : (_dur > 300 ? 300 : _dur));
        entryFee = _entryFee; // this is in wei
        owner = msg.sender;
    }
```
```
   function playGame(uint id) isPlayer() isGameTime() {
...
        // If the function is called after the end of the game, the
        // current 'current' wins the pot and resets the game.
        if (now >= endTime) {
            if (players[current].addr.send(entryFee*nPlayers))
                nPlayers = 0;
        }
    }
```

The game can be set to run over a period of 30 seconds to 5 minutes and ends when a duration of initial block time + game duration is exceed. Given that miners at not required by the protocol to prove an accurate timestamp at the time of mining, there is no guarantee that the subsequent timestamps will be linearly or even statistically *increasing* over such a short period.

Consider the contract is launched with 30 second duration
Let `blk1` be the timestamp as seen by last player to enter. Time `end == blk1 + 30 seconds`.
Note that the block containing the last player actual TX is `blk2` with a timestamp ~12:00:14 but under normal statistical variance may well exceed 12:00:30.  This means the very first call to `playGame` on `blk2` will ensure a win for player 1.

Consider the contract is launched with 300 second duration or approximately 21 blocks.
There are 21 chances of a random miner's recording a misconfigured timestamp beyond the contract's duration and forcing an early end to the game.  This is not a security risk but might present unexpected behaviour. 

```
   function playGame(uint id) isPlayer() isGameTime() {
```

parameter `uint id` is not used in the function

**Comment by tjayrush** [comment]
I love this issue. I think I am going to leave it in here, but use it with a more advanced group to teach the issue of being aware that one cannot even trust the miners when one is writing solidity code. I am going to use the issue description as comments in the code.

**Comment by o0ragman0o** [comment]
Yes it is an advanced topic and one that won't really present if you are teaching on a private chain whose nodes timestamps you can control.
