### ISSUE TITLE
Setting storage variables to zero makes gas usage uneven

### ISSUE THREAD

**Issue by veox** [Great-Hill-Corporation/nameGame#7]
There are several places where storage variables are set to `0`. Arising issues:

1. Gas fees for players are uneven (transactions that clear storage get a gas reimbursement, transactions that set to non-zero from zero use more gas).

From the [yellowpaper](http://gavwood.com/Paper.pdf) (page 10, section 9.2):

> Storage fees have a slightly nuanced behaviour|to in-
centivise minimisation of the use of storage (which corre-
sponds directly to a larger state database on all nodes),
the execution fee for an operation that clears an entry in
the storage is not only waived, a quali ed refund is given;
in  fact,  this  refund  is  e ectively  paid  up-front  since  the
initial usage of a storage location costs substantially more
than normal usage.
See Appendix H for a rigorous de nition of the EVM
gas cost.

2. Using `0` to specify a state machine's state may have unexpected results in Solidity, since that's the default (meaning "not set") for state variables. E.g., a dapp "thinks" that `current` is `0`, but it was never set in the first place. The contract's logic may need review in light of this fact.

-----

BTW, this means that in `joinGame()`, the following does nothing for the first ever game, since `current` is still `0` after contract creation:

```
if (nPlayers==1) {
    // First player becomes first current
    current = 0;
}
```
However, `playGame()` resets `nPlayers` (but not `current`!) after game ends, so the above code is needed. I suggest creating `resetGame()` for this particular case, and moving all relevant logic there.

**Comment by veox** [comment]
OTOH, uneven gas use may be desirable as an entry point in classroom discussion.

**Comment by tjayrush** [comment]
I never heard of this issue of uneven gas use. I am not going to fix it, but I am going to document it because I think it does allow for a good classroom discussion. Thanks.
